replicaCount: 1

image:
  repository: defendersd/dev-budget-tracker-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: internal-budget-tracker.home.coded-by-danil.dev
      paths:
        - path: /
          pathType: Prefix

