replicaCount: 1

image:
  repository: defendersd/dev-budget-tracker-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-budget-tracker.home.coded-by-danil.dev
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: "25m"
    memory: "64Mi"
  limits:
    cpu: "50m"
    memory: "128Mi"

configMapData:
  ASPNETCORE_ENVIRONMENT: "DockerDev"

secretName: budget-tracker-secret

