replicaCount: 1

image:
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: "25m"
    memory: "64Mi"
  limits:
    cpu: "50m"
    memory: "128Mi"

configMapData:
  ASPNETCORE_ENVIRONMENT: "DockerDev"

secretName: basic-secret

