replicaCount: 1

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "25m"
    memory: "64Mi"
  limits:
    cpu: "50m"
    memory: "128Mi"

configMapData:
  ASPNETCORE_ENVIRONMENT: "DockerDev"

secretName: basic-secret

