replicaCount: 1

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "150m"
    memory: "512Mi"

configMapData:
  ASPNETCORE_ENVIRONMENT: "DockerDev"

secretName: basic-secret

